CREATE DATABASE laugh_plz;

CREATE TABLE laughs(
    id    	INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    laugh 	VARCHAR(280) NOT NULL
);

INSERT INTO laughs(laugh) VALUES ('KKKKKKKKKK');
INSERT INTO laughs(laugh) VALUES ('ESSA FOI DE FUDE EMKKKKKKKKKKKKK');
INSERT INTO laughs(laugh) VALUES ('KARALHOPERDIKKKKKKKKKKKKKKKKKKKK');
INSERT INTO laughs(laugh) VALUES ('TOMANOCUEMVEIOKKKKKKKKKKKKKKKKKK');
INSERT INTO laughs(laugh) VALUES ('VUEIKKKKKKKKKKKKKKKKKKKKKKKKKKKK');
INSERT INTO laughs(laugh) VALUES ('PORCAPIPAKKKKKKKKKKKKKKKKKKKKKKK');
INSERT INTO laughs(laugh) VALUES ('PUTAQUEOPARIOOKKKKKKKKKKKKKKKKKKKKKKKKKK');
INSERT INTO laughs(laugh) VALUES ('PERDI AS ESTRIBERAKKKKKKKKKKKKKKKKKKKKKK');
INSERT INTO laughs(laugh) VALUES ('AKaKAkAkKakKAkAkKAkA');
INSERT INTO laughs(laugh) VALUES ('LMAO XDXD LOLOLOL');
INSERT INTO laughs(laugh) VALUES ('KOOKKKKKKKKKKKKKKKKKKKKKKKKKKKKK');
INSERT INTO laughs(laugh) VALUES ('KEK');
INSERT INTO laughs(laugh) VALUES ('KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK');
INSERT INTO laughs(laugh) VALUES ('Cramenha! KKKKKKKKKKKKKKKKKKKKKKKKKK');
INSERT INTO laughs(laugh) VALUES ('- Pô, que engraçado! (Kkk)  ?!?');
INSERT INTO laughs(laugh) VALUES ('?%??%??%??%??%??%??%??%??%??%?');
INSERT INTO laughs(laugh) VALUES ('?%??%??%??%??%??%??%??%??!??!??!??!?');
INSERT INTO laughs(laugh) VALUES ('ZAP?%??%??%??%??%??%??%??%??%??%?');
INSERT INTO laughs(laugh) VALUES ('KKKKKKKKKKKKKKK ?%??%??%??%??%??%?');
INSERT INTO laughs(laugh) VALUES ('?%??!?');